name: "Sync GitHub Issue"
description: "Sync GitHub Parent Issue to Child Issue"
author: "kudoas"
inputs:
  repository:
    description: "Repository name with owner. For example, kudoas/gis'"
    default: ${{ github.repository }}
  issue:
    description: "The number that identifies the issue. Specify the child issue you wish to synchronize with the parent issue"
    default: ${{ github.event.issue.number }}
  token:
    description: "GitHub Token"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
