name: CI
on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: actions/checkout@v4
      - name: Build
        run: |
          go get -d -v
          CGO_ENABLED=0 go build -ldflags="-w -s" -v -o app .
      - name: Integration Test
        run: |
          INPUT_TOKEN=${{ secrets.PAT }} INPUT_REPOSITORY=kudoas/sync-issue-field INPUT_ISSUE=3 ./app
